// postsSlice.js
// Redux slice responsible for managing Reddit post data
// Handles fetching posts from the Reddit API and storing them in the global state
// Also manages loading and error states
// Uses createAsyncThunk for asynchronous actions to fetch posts and comments from a specific subreddit using the Reddit JSON API
// The fetchPosts thunk takes subreddit and filter parameters to fetch posts based on user selection
// The fetchComments thunk takes a postId to fetch comments for a specific post
// The slice's extraReducers handle the pending, fulfilled, and rejected states of these async thunks to update the state accordingly
// The posts state includes an array of posts, a loading boolean, and an error message
// The posts are stored in the state with their comments nested inside each post object when fetched

import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";

// Initial state for the posts slice
const initialState = {
  // Array to hold the list of posts fetched from the Reddit API
  posts: [],
  loading: false,
  error: null,
};

// Async thunk to fetch posts from the Reddit API based on subreddit and filter
export const fetchPosts = createAsyncThunk(
  "posts/fetchPosts",
  // The async function takes an object with subreddit and filter properties
  async ({ subreddit, filter }) => {
    const response = await fetch(
      `https://www.reddit.com/r/${subreddit}/${filter}.json` // Reddit API endpoint for fetching posts based on subreddit and filter
    );

    // Parse the JSON response from the Reddit API
    const data = await response.json();

    // Map the response data to extract the relevant post information and return it as an array of post objects
    return data.data.children.map((post) => post.data);
  }
);

// Async thunk to fetch comments for a specific post based on postId
export const fetchComments = createAsyncThunk(
  "posts/fetchComments",
  // The async function takes a postId as an argument to fetch comments for that specific post
  async (postId) => {
    // Fetch comments from the Reddit API for the given postId
    const response = await fetch(
      `https://www.reddit.com/comments/${postId}.json`
    );

    // Parse the JSON response from the Reddit API
    const json = await response.json();

    // Return an object containing the postId and an array of comments extracted from the response
    return {
      postId,
      comments: json[1].data.children
        .filter((child) => child.kind === 't1') // Filter to include only comment objects
        .map((child) => child.data),
    };
  }
);

// Create the posts slice using createSlice from Redux Toolkit
const postsSlice = createSlice({
  // The name of the slice is "posts"
  name: "posts",
  initialState,
  reducers: {}, // no manual reducers needed
  extraReducers: (builder) => {
    // Handle the pending, fulfilled, and rejected states of the fetchPosts async thunk to update the loading and error states accordingly
    builder
      // When fetchPosts is pending, set loading to true and clear any previous errors
      .addCase(fetchPosts.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      // When fetchPosts is fulfilled, set loading to false and update the posts array with the fetched posts
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.loading = false;
        state.posts = action.payload;
      })
      // When fetchPosts is rejected, set loading to false and update the error state with an error message
      .addCase(fetchPosts.rejected, (state) => {
        state.loading = false;
        state.error = "Failed to fetch posts";
      })
      // Handle the fulfilled state of the fetchComments async thunk to update the comments for the corresponding post in the posts array
      .addCase(fetchComments.fulfilled, (state, action) => {
        const { postId, comments } = action.payload;

        // Find the post in the posts array that matches the postId and update its comments property with the fetched comments
        const post = state.posts.find((p) => p.id === postId);

        // If the post is found, update its comments property with the fetched comments
        if (post) {
          post.comments = comments;
        }
      })
  },
});

// Export the reducer function generated by createSlice to be used in the Redux store configuration
export default postsSlice.reducer;